version: "3.8"

services:
  db:
    image: postgres:16
    container_name: opin_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: opin_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/init_full.sql:/docker-entrypoint-initdb.d/init.sql
      - opin_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d opin_local" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: postgrest/postgrest
    container_name: opin_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:password@db:5432/opin_local
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
      PGRST_JWT_SECRET: "this-is-a-super-secret-jwt-key-for-local-development-12345"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: .
    container_name: opin_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  opin_postgres_data:
    driver: local
